# 07.错误恢复
* 实现错误处理机制
* Ref: [Go语言动手写Web框架 - Gee第七天 错误恢复(Panic Recover)](https://geektutu.com/post/gee-day7.html)
## 错误处理机制
Go语言对于一些普通的错误, 一般是通过函数`error`类型的返回值来判断的, 若返回非`nil`则证明发生了错误, 用于上层进行处理, 而这一般是对于一些可以预测的错误. 而对于一些无法预测的错误, 向C++、Java使用的是 `try/catch`的异常处理机制, 而在Go值则是通过 `defer-panic-and-recover` 机制处理错误. 该部分属于Go语法特性, 在此不多赘述, 详见 [第13章：错误处理与测试 - Go入门指南](https://www.bookstack.cn/read/the-way-to-go_ZH_CN/eBook-13.0.md).
在Web框架中, 同样需要错误处理机制, 用于应对框架本身可能存在的bug, 以及用户非法输入导致的异常.
在该框架中, 利用Go的`defer-panic-and-recover`机制, 进行简单的错误处理: 在错误发生时, 向用户返回 Internal Server Error, 并且在日志中打印必要的错误信息, 方便进行错误定位. 而错误处理功能选择了和日志记录一样, 以中间件的方式嵌入到框架中.
## 错误处理中间件
将错误处理函数封装成一个中间件函数, 添加到框架主体(即根路由分组)上.
* `Recovery()`为返回错误处理中间件函数的函数. 在错误处理中间件函数中, 主体为`defer`语句后跟的匿名函数, 用于处理错误. 在其中, 又使用`recover()`函数进行异常恢复. 其中使用`trace()`函数打印调用栈信息, 方便debug, 进而使用`Fail()`函数终止本次请求的处理函数的执行.
* `trace()`函数主要利用标准库`runtime`中的函数来打印错误发生的调用栈信息.
    * `func Callers(skip int, pc []uintptr) int`: 把当前go程调用栈上的调用栈标识符填入切片`pc`中, 返回写入到`pc`中的项数. 实参`skip`为开始在`pc`中记录之前所要跳过的栈帧数. `0`表示`Callers`自身的调用栈, `1`表示`Callers`所在的调用栈.
    * `func FuncForPC(pc uintptr) *Func`: 返回一个表示调用栈标识符`pc`对应的调用栈的`*Func`; 如果该调用栈标识符没有对应的调用栈, 函数会返回`nil`. 每一个调用栈必然是对某个函数的调用.
    * `func (f *Func) Name() string`: 返回该调用栈所调用的函数的名字.
    * `func (f *Func) FileLine(pc uintptr) (file string, line int)`: 返回该调用栈所调用的函数的源代码文件名和行号.
    * `strings.Builder`: 和Java中相同, Go中的string类型其值是只读不可变的, 因此其相应的拼接等操作实际上是创建了新的字符串. 而`Builder`类型则是Go专门用于字符串拼接的结构, 效率更高. 使用`(*Builder).WriteString`向其添加字符串.
### recovery.go
/day7/gee/recovery.go

```go
package gee

import (
	"fmt"
	"log"
	"net/http"
	"runtime"
	"strings"
)

func trace(message string) string {
	var pcs [32]uintptr //指针
	//获取调用栈指针(跳过前3个)
	n := runtime.Callers(3, pcs[:])
	var str strings.Builder  //快速字符串拼接
	str.WriteString(message) //拼接字符串
	str.WriteString("\nTraceback:")
	for _, pc := range pcs[:n] {
		fn := runtime.FuncForPC(pc)		//返回栈指针对应函数
		file, line := fn.FileLine(pc)	//文件及行号
		str.WriteString(fmt.Sprintf("\n\t%s:%d", file, line))
	}
	return str.String()	//转字符串
}

func Recovery() HandlerFunc {
	return func(c *Context) {
		defer func() {
			if err := recover(); err != nil {
				message := fmt.Sprintf("%s", err)
				log.Printf("%s\n\n", trace(message))
				c.Fail(http.StatusInternalServerError,
					"Internal Server Error")
			}
		}()
		c.Next()
	}
}
```
### gee.go
/day7/gee/gee.go
```go
//默认框架
func Default() *Engine {
	engine:=New()
	//带日志记录和异常恢复
	engine.Use(Logger(), Recovery())
	return engine
}
```

## 框架使用
/day7/main.go
```go
package main

import (
	"gee"
	"net/http"
)

func main() {
	r:=gee.Default()	//带Logger和Recovery的框架
	r.GET("/", func(c *gee.Context) {
		c.String(http.StatusOK,"Hello Gee\n")
	})
	r.GET("/panic", func(c *gee.Context) {
		names:=[]string{"geektutu"}
		c.String(http.StatusOK, names[100])		//数组越界会引发panic
	})
	r.GET("/json", func(c *gee.Context) {
		c.JSON(http.StatusOK,gee.H{
			"name":"gee",
		})
	})
	r.Run(":9999")
}
```
框架加入了带错误恢复的中间件. 此处路径`/panic`由于用户的数组访问越界会引发panic, 最终由错误处理中间件进行处理, 在控制台输出调用栈信息如下, 并使程序继续执行.
```
2021/02/12 19:32:21 runtime error: index out of range [100] with length 1
Traceback:
	D:/Download/Go/src/runtime/panic.go:969
	D:/Download/Go/src/runtime/panic.go:88
	E:/Computer/Go/GeeExp/day7/main.go:15
	E:/Computer/Go/GeeExp/day7/gee/context.go:36
	E:/Computer/Go/GeeExp/day7/gee/recovery.go:37
	E:/Computer/Go/GeeExp/day7/gee/context.go:36
	E:/Computer/Go/GeeExp/day7/gee/logger.go:14
	E:/Computer/Go/GeeExp/day7/gee/context.go:36
	E:/Computer/Go/GeeExp/day7/gee/router.go:91
	E:/Computer/Go/GeeExp/day7/gee/gee.go:105
	D:/Download/Go/src/net/http/server.go:2808
	D:/Download/Go/src/net/http/server.go:1896
	D:/Download/Go/src/runtime/asm_amd64.s:1374
```